"""Add owner to data chart

Revision ID: 1494f4db570b
Revises: fd53a98a26fc
Create Date: 2021-05-11 13:22:38.885512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1494f4db570b'
down_revision = 'fd53a98a26fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_chart', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'data_chart', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_chart', type_='foreignkey')
    op.drop_column('data_chart', 'owner_id')
    # ### end Alembic commands ###
