"""add user to table

Revision ID: 3218c6b0ba47
Revises: 66e54c03ba78
Create Date: 2021-05-06 14:13:11.828220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3218c6b0ba47'
down_revision = '66e54c03ba78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_table', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dataset_table', 'user', ['owner_id'], ['id'])
    op.alter_column('user_rating', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_rating', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'dataset_table', type_='foreignkey')
    op.drop_column('dataset_table', 'owner_id')
    # ### end Alembic commands ###
