"""Data chart

Revision ID: fd53a98a26fc
Revises: 3218c6b0ba47
Create Date: 2021-05-11 13:18:25.891210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd53a98a26fc'
down_revision = '3218c6b0ba47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_chart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('chart_type_id', sa.Integer(), nullable=False),
    sa.Column('dataset_table_id', sa.Integer(), nullable=False),
    sa.Column('x_dataset_column_v_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('y_dataset_column_v_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['chart_type_id'], ['chart_type.id'], ),
    sa.ForeignKeyConstraint(['dataset_table_id'], ['dataset_table.id'], ),
    sa.ForeignKeyConstraint(['x_dataset_column_v_id'], ['dataset_column_versioned.id'], ),
    sa.ForeignKeyConstraint(['y_dataset_column_v_id'], ['dataset_column_versioned.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_chart')
    op.drop_table('chart_type')
    # ### end Alembic commands ###
